test = {   'name': 'q_grammar_spec_2',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': ">>> _g, _a = xform.parse_augmented_grammar(grammar_spec_2, globals=globals());\n>>> print(list(_g.productions())[11])\nLOC -> 'Boston'\n",
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': ">>> _g, _a = xform.parse_augmented_grammar(grammar_spec_2, globals=globals());\n>>> print(list(_g.productions())[12])\nLOC -> 'New' 'York'\n",
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': ">>> _g, _a = xform.parse_augmented_grammar(grammar_spec_2, globals=globals());\n>>> print(list(_g.productions())[13])\nLOC -> 'Tel' 'Aviv'\n",
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
