test = {   'name': 'complete_derivation',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> all([isinstance(N__capital(object), bool) for object in sorted(Object)])\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> isinstance(NP__a_capital(N__capital), bool)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> isinstance(NP__every_flight(VP__leaves_from_a_capital), bool)\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> isinstance(S__every_flight_leaves_from_a_capital, bool)\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
